### ISSUE TITLE
Is this promised based? or is the API 100% synchronous?

### ISSUE THREAD

**Issue by ORESoftware** [ForbesLindesay/taxi-rank#16]
If this is promised based, perhaps include an example using Promises and where they apply?

**Comment by ForbesLindesay** [comment]
This is http based, i.e. it's just a server.  Whether it uses Promises, synchronous code, or something else, depends entirely on what client you use.

The recommended client is cabbie, which comes in both "sync" and "async" mode (the latter of which uses promises).  See https://cabbiejs.org/ (I'm still working on full documentation for cabbie).

**Comment by ORESoftware** [comment]
I meant specifically:

```
  // navigate to a url in the currently active window
  driver.browser.activeWindow.navigateTo('http://example.com');
```

does that return a Promise or...? seems very unclear

**Comment by ForbesLindesay** [comment]
If you use cabbie-sync it is synchronous, if you use cabbie-async it is asynchronous. If you use another web driver client it can vary.

**Comment by ForbesLindesay** [comment]
The readme example is synchronous.
